"""add_discount_savings_to_bills

Revision ID: 763726882d3e
Revises: 7804630f14e7
Create Date: 2025-06-08 18:19:49.871845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763726882d3e'
down_revision: Union[str, None] = '7804630f14e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('discount_savings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'discount_savings')
    # ### end Alembic commands ### 