"""add_time_column_to_bills

Revision ID: 7804630f14e7
Revises: create_uuid_tables
Create Date: 2025-06-08 18:15:26.249672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7804630f14e7'
down_revision: Union[str, None] = 'create_uuid_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('bill_categories',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'category_id')
    )
    op.drop_index(op.f('ix_bills_total_amount'), table_name='bills')
    op.drop_index(op.f('ix_bills_transaction_id'), table_name='bills')
    op.drop_column('bills', 'currency')
    op.drop_column('bills', 'discount_savings')
    op.drop_column('bills', 'approval_code')
    op.drop_column('bills', 'card_last_four')
    op.alter_column('line_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_line_items_bill_id'), 'line_items', ['bill_id'], unique=False)
    op.drop_column('line_items', 'updated_at')
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('line_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_line_items_bill_id'), table_name='line_items')
    op.alter_column('line_items', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('bills', sa.Column('card_last_four', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('approval_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('discount_savings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_bills_transaction_id'), 'bills', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_bills_total_amount'), 'bills', ['total_amount'], unique=False)
    op.drop_table('bill_categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ### 