"""add_google_sheets_columns_to_users

Revision ID: 9e2587d1c0a2
Revises: 763726882d3e
Create Date: 2025-07-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9e2587d1c0a2'
down_revision: Union[str, None] = '763726882d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('sheets_spreadsheet_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auto_export_to_sheets', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_export_to_sheets')
    op.drop_column('users', 'sheets_spreadsheet_id')
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    # ### end Alembic commands ### 