"""add_export_flags_to_bills

Revision ID: e16a5ff5ad3b
Revises: 9e2587d1c0a2
Create Date: 2025-07-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e16a5ff5ad3b'
down_revision: Union[str, None] = '9e2587d1c0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('exported_to_sheets', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('bills', sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'exported_at')
    op.drop_column('bills', 'exported_to_sheets')
    # ### end Alembic commands ### 